import Foundation

enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        switch language {
        case .english:
            return key
        case .simplifiedChinese:
            return zhCN[key] ?? key
        }
    }

    private static let zhCN: [String: String] = [
        "Today Radar": "今日雷达",
        "Search Lab": "调研搜索",
        "Research Profiles": "研究方向",
        "Memory": "长期记忆",
        "Read Papers": "已读文章",
        "Settings": "设置",
        "Ranked candidates from local memory and official APIs.": "基于本地记忆和官方 API 排序的候选论文。",
        "Run relevance search or broader exploration against local and live sources.": "在本地库和在线来源中做相关性搜索或探索性搜索。",
        "Each profile has its own terms, weights, seeds, and exclusions.": "每个研究方向都有独立关键词、权重、种子论文和排除项。",
        "Profile-level overviews, claims, open questions, and weekly digests.": "按研究方向查看综述、论断、开放问题和周报。",
        "Papers that have been read or integrated into your knowledge system.": "已经读过或已融入知识体系的文章。",
        "Profile": "研究方向",
        "Sort by": "排序",
        "Time": "时间",
        "Refresh": "刷新",
        "Demo": "示例",
        "Run Radar": "运行雷达",
        "Query, DOI, arXiv ID, author, or topic": "输入问题、DOI、arXiv ID、作者或主题",
        "Mode": "模式",
        "Relevance": "相关性",
        "Explore": "探索",
        "Live APIs": "在线 API",
        "Online Search": "在线搜索",
        "Search": "搜索",
        "New Profile": "新建方向",
        "No profile": "没有研究方向",
        "No papers yet": "还没有论文",
        "No memory notes yet.": "还没有长期记忆笔记。",
        "Select a memory note to preview.": "选择一条长期记忆后再预览全文。",
        "Loading memory note": "正在加载长期记忆",
        "Synthesize": "生成综述",
        "DeepSeek": "DeepSeek",
        "API key": "API Key",
        "Save to Keychain": "保存到钥匙串",
        "Language": "语言",
        "Interface language": "界面语言",
        "Exports": "导出",
        "Obsidian vault path": "Obsidian 仓库路径",
        "Export Obsidian": "导出 Obsidian",
        "Export Zotero": "导出 Zotero",
        "Zotero Import": "Zotero 导入",
        "Choose Zotero Export": "选择 Zotero 导出文件",
        "Choose Zotero Export File or Folder": "选择 Zotero 导出文件或文件夹",
        "Integrate Selected": "融入长期记忆",
        "Save": "保存",
        "Mark read": "标为已读",
        "Like": "喜欢",
        "Hide": "隐藏",
        "Analyze": "解读",
        "Assess usefulness": "评估用途",
        "Candidates": "候选",
        "Saved": "已保存",
        "Memory notes": "记忆笔记",
        "Name": "名称",
        "Weight": "权重",
        "Include terms": "包含词",
        "Exclude terms": "排除词",
        "Seed papers": "种子论文",
        "Watch authors": "关注作者",
        "Watch labs": "关注实验室",
        "Save Profile": "保存方向",
        "Delete": "删除",
        "Cancel": "取消",
        "Delete profile": "删除研究方向",
        "Edit": "编辑",
        "Delete profile?": "删除这个研究方向？",
        "This removes the profile and its profile-specific scores, feedback, and notes. Papers stay in the library.": "这会删除该方向及其评分、反馈和笔记；论文库中的论文会保留。",
        "Create": "创建",
        "Generated profile": "已生成研究方向",
        "Generating profile": "生成研究方向",
        "Generate Profile": "生成研究方向",
        "Describe the research direction first.": "请先描述研究方向。",
        "Create manually or generate search keywords from a natural-language direction.": "手动创建，或根据自然语言研究方向生成检索关键词。",
        "Creation mode": "创建方式",
        "Natural-language description": "自然语言描述",
        "Manual fields": "手动字段",
        "Manual mode creates a blank profile that you can edit in the profile editor.": "手动模式会创建一个空白研究方向，随后可在编辑器中填写。",
        "Profile description tips": "研究方向描述建议",
        "Describe the topic, methods, organism/data type, must-have terms, terms to exclude, and optionally famous scholars or labs. Mention variants if you care about them; the generator will also add common OR variants such as single cell OR single-cell.": "建议描述主题、方法、物种/数据类型、必须包含的词、需要排除的词，并可选添加领域知名学者或实验室。可以写出你关心的变体；生成器也会补常见 OR 变体，比如 single cell OR single-cell。",
        "arXiv query": "arXiv 检索式",
        "bioRxiv query": "bioRxiv 检索式",
        "Add item": "添加条目",
        "Add": "添加",
        "Remove": "移除",
        "Ready": "就绪",
        "Initializing database": "初始化数据库",
        "Refreshing": "刷新",
        "Loading demo papers": "加载示例论文",
        "Running radar": "运行雷达",
        "Searching": "搜索中",
        "Saving profile": "保存研究方向",
        "Creating profile": "创建研究方向",
        "Deleting profile": "删除研究方向",
        "Saving feedback": "保存反馈",
        "Analyzing paper": "解读论文",
        "Assessing paper usefulness": "评估论文用途",
        "Synthesizing weekly memory": "生成周度记忆",
        "Exporting Obsidian vault": "导出 Obsidian 仓库",
        "Exporting Zotero files": "导出 Zotero 文件",
        "Importing Zotero file": "导入 Zotero 文件",
        "Importing Zotero export": "导入 Zotero 导出内容",
        "Integrating Zotero papers": "融合 Zotero 论文",
        "Preparing long-term memory integration": "准备融入长期记忆",
        "Long-term memory integration": "长期记忆融合",
        "Long-term memory integration complete.": "长期记忆融合完成。",
        "Long-term memory integration failed.": "长期记忆融合失败。",
        "Large Zotero imports may take several minutes because local PDFs are read first and DeepSeek synthesis runs in batches.": "大量 Zotero 文献可能需要几分钟：程序会先读取本地 PDF，再分批调用 DeepSeek 综合。",
        "Preparing": "准备中",
        "Saving selections": "保存选择",
        "Refreshing scores": "刷新评分",
        "Reading PDFs": "读取 PDF",
        "Batch synthesis": "分批综合",
        "Final memory merge": "最终合并",
        "Writing memory": "写入记忆",
        "Exporting Obsidian": "导出 Obsidian",
        "Complete": "完成",
        "Failed": "失败",
        "Done": "完成",
        "Enter a query first.": "请先输入搜索内容。",
        "DeepSeek key saved to Keychain.": "DeepSeek API Key 已保存到钥匙串。",
        "DeepSeek key cleared.": "DeepSeek API Key 已清空。",
        "How to get a DeepSeek key": "如何填写 DeepSeek API",
        "Interface": "界面",
        "Show status hints": "显示状态提示",
        "Status hints include the lower-left sidebar hint and the bottom status bar.": "状态提示包括左下角提示和底部状态栏。",
        "Font size": "字体大小",
        "Appearance": "外观",
        "Follow System": "跟随系统",
        "Light Appearance": "浅色模式",
        "Dark Appearance": "深色模式",
        "Reading and synthesis API key": "阅读与综述 API Key",
        "Fast profile-generation API key": "快速生成方向 API Key",
        "DeepSeek keys saved to Keychain.": "DeepSeek API Key 已保存到钥匙串。",
        "Paste your DeepSeek API key here, then press Save to Keychain. The app stores it in macOS Keychain under service LiteratureRadarDeepSeekAPIKey. For command-line use, you can also run: export DEEPSEEK_API_KEY=sk-...": "阅读与综述 Key 用于论文解读和长期记忆；快速生成方向 Key 用于 deepseek-v4-flash 生成检索式。快速 Key 留空时会回退到阅读与综述 Key。命令行也可使用 DEEPSEEK_API_KEY 或 DEEPSEEK_FLASH_API_KEY。",
        "Imported papers": "已导入论文",
        "Select papers to merge into the current profile's long-term memory.": "选择要融入当前研究方向长期记忆的论文。",
        "No Zotero import yet. Export RIS, BibTeX, or CSL JSON from Zotero and choose it here.": "还没有导入 Zotero 文件。请先从 Zotero 导出 RIS、BibTeX 或 CSL JSON，然后在这里选择。",
        "No Zotero import yet. Export BibTeX, RIS, or CSL JSON from Zotero and choose the export file or folder here. Local PDFs under files/ are read automatically when available.": "还没有导入 Zotero。请从 Zotero 导出 BibTeX、RIS 或 CSL JSON，然后在这里选择导出文件或文件夹；files/ 下的本地 PDF 会在可读取时自动读取。",
        "Zotero export tutorial": "Zotero 导出教程",
        "In Zotero, select papers, choose File > Export Items..., pick RIS, BibTeX, or CSL JSON, then import that file here.": "在 Zotero 中选中文献，点击 File > Export Items...，选择 RIS、BibTeX 或 CSL JSON，然后在这里导入该文件。",
        "In Zotero, select papers, choose File > Export Items..., pick BibTeX, RIS, or CSL JSON. If Zotero creates a folder with a .bib file plus a files/ PDF folder, you can select either the folder or the .bib file here.": "在 Zotero 中选中文献，点击 File > Export Items...，选择 BibTeX、RIS 或 CSL JSON。如果 Zotero 生成了一个包含 .bib 文件和 files/ PDF 文件夹的导出文件夹，这里既可以选择该文件夹，也可以选择里面的 .bib 文件。",
        "Initializing local database only. Use Demo or Run Radar after the app opens.": "仅初始化本地数据库。打开后可点击“示例”或“运行雷达”。"
    ]
}
