import Foundation

enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        switch language {
        case .english:
            return key
        case .simplifiedChinese:
            return zhCN[key] ?? key
        }
    }

    private static let zhCN: [String: String] = [
        "Today Radar": "今日雷达",
        "Search Lab": "调研搜索",
        "Research Profiles": "研究方向",
        "Memory": "长期记忆",
        "Read Papers": "已读文章",
        "Settings": "设置",
        "Ranked candidates from local memory and official APIs.": "基于本地记忆和联网搜索排序的候选论文。",
        "Prioritizes newly found online papers you have not read; local papers are only shown as a small supplement.": "优先显示从网上新搜到、你还没读过的论文；本地论文只少量补充。",
        "Run relevance search or broader exploration against local and live sources.": "在本地库和在线来源中做相关性搜索或探索性搜索。",
        "Each profile has its own terms, weights, seeds, and exclusions.": "每个研究方向都有独立关键词、权重、种子论文和排除项。",
        "Profile-level overviews, claims, open questions, and weekly digests.": "按研究方向查看综述、论断、开放问题和周报。",
        "Papers that have been read or integrated into your knowledge system.": "已经读过或已融入知识体系的文章。",
        "Profile": "研究方向",
        "Sort by": "排序",
        "Time": "时间",
        "Refresh": "刷新",
        "Demo": "示例",
        "Run Radar": "运行雷达",
        "Query, DOI, arXiv ID, author, or topic": "输入问题、DOI、arXiv ID、作者或主题",
        "Mode": "模式",
        "Relevance": "相关性",
        "Explore": "探索",
        "Live APIs": "联网搜索",
        "Search online": "联网搜索",
        "Online Search": "在线搜索",
        "Search": "搜索",
        "New Profile": "新建方向",
        "No profile": "没有研究方向",
        "No papers yet": "还没有论文",
        "No memory notes yet.": "还没有长期记忆笔记。",
        "Select a memory note to preview.": "选择一条长期记忆后再预览全文。",
        "Loading memory note": "正在加载长期记忆",
        "Synthesize": "生成综述",
        "DeepSeek": "DeepSeek",
        "API key": "API Key",
        "Save to Keychain": "保存到钥匙串",
        "Language": "语言",
        "Interface language": "界面语言",
        "Exports": "导出",
        "Obsidian vault path": "Obsidian 仓库路径",
        "Export Obsidian": "导出 Obsidian",
        "Export Zotero": "导出 Zotero",
        "Zotero Import": "Zotero 导入",
        "Choose Zotero Export": "选择 Zotero 导出文件",
        "Choose Zotero Export File or Folder": "选择 Zotero 导出文件或文件夹",
        "Integrate Selected": "融入长期记忆",
        "Save": "保存",
        "Mark read": "标为已读",
        "Like": "喜欢",
        "Hide": "隐藏",
        "Analyze": "解读",
        "Assess usefulness": "评估用途",
        "Candidates": "候选",
        "Saved": "已保存",
        "Memory notes": "记忆笔记",
        "Name": "名称",
        "Weight": "权重",
        "Include terms": "包含词",
        "Exclude terms": "排除词",
        "Seed papers": "种子论文",
        "Watch authors": "关注作者",
        "Watch labs": "关注实验室",
        "Save Profile": "保存方向",
        "Delete": "删除",
        "Cancel": "取消",
        "Delete profile": "删除研究方向",
        "Edit": "编辑",
        "Delete profile?": "删除这个研究方向？",
        "This removes the profile and its profile-specific scores, feedback, and notes. Papers stay in the library.": "这会删除该方向及其评分、反馈和笔记；论文库中的论文会保留。",
        "Create": "创建",
        "Generated profile": "已生成研究方向",
        "Generating profile": "生成研究方向",
        "Generate Profile": "生成研究方向",
        "Describe the research direction first.": "请先描述研究方向。",
        "Create manually or generate search keywords from a natural-language direction.": "手动创建，或根据自然语言研究方向生成检索关键词。",
        "Creation mode": "创建方式",
        "Natural-language description": "自然语言描述",
        "Manual fields": "手动字段",
        "Manual mode creates a blank profile that you can edit in the profile editor.": "手动模式会创建一个空白研究方向，随后可在编辑器中填写。",
        "Profile description tips": "研究方向描述建议",
        "Describe the topic, methods, organism/data type, must-have terms, terms to exclude, and optionally famous scholars or labs. Mention variants if you care about them; the generator will also add common OR variants such as single cell OR single-cell.": "建议描述主题、方法、物种/数据类型、必须包含的词、需要排除的词，并可选添加领域知名学者或实验室。可以写出你关心的变体；生成器也会补常见 OR 变体，比如 single cell OR single-cell。",
        "arXiv query": "arXiv 检索式",
        "bioRxiv query": "bioRxiv 检索式",
        "Add item": "添加条目",
        "Add": "添加",
        "Remove": "移除",
        "Ready": "就绪",
        "Initializing database": "初始化数据库",
        "Refreshing": "刷新",
        "Loading demo papers": "加载示例论文",
        "Running radar": "运行雷达",
        "Searching": "搜索中",
        "Saving profile": "保存研究方向",
        "Creating profile": "创建研究方向",
        "Deleting profile": "删除研究方向",
        "Saving feedback": "保存反馈",
        "Analyzing paper": "解读论文",
        "Assessing paper usefulness": "评估论文用途",
        "Synthesizing weekly memory": "生成周度记忆",
        "Exporting Obsidian vault": "导出 Obsidian 仓库",
        "Exporting Zotero files": "导出 Zotero 文件",
        "Importing Zotero file": "导入 Zotero 文件",
        "Importing Zotero export": "导入 Zotero 导出内容",
        "Integrating Zotero papers": "融合 Zotero 论文",
        "Preparing long-term memory integration": "准备融入长期记忆",
        "Long-term memory integration": "长期记忆融合",
        "Long-term memory integration complete.": "长期记忆融合完成。",
        "Long-term memory integration failed.": "长期记忆融合失败。",
        "Large Zotero imports may take several minutes because local PDFs are read first and DeepSeek synthesis runs in batches.": "大量 Zotero 文献可能需要几分钟：程序会先读取本地 PDF，再分批调用 DeepSeek 综合。",
        "Preparing": "准备中",
        "Saving selections": "保存选择",
        "Refreshing scores": "刷新评分",
        "Reading PDFs": "读取 PDF",
        "Batch synthesis": "分批综合",
        "Final memory merge": "最终合并",
        "Writing memory": "写入记忆",
        "Exporting Obsidian": "导出 Obsidian",
        "Complete": "完成",
        "Failed": "失败",
        "Done": "完成",
        "Enter a query first.": "请先输入搜索内容。",
        "DeepSeek key saved to Keychain.": "DeepSeek API Key 已保存到钥匙串。",
        "DeepSeek key cleared.": "DeepSeek API Key 已清空。",
        "How to get a DeepSeek key": "如何填写 DeepSeek API",
        "Interface": "界面",
        "Show status hints": "显示状态提示",
        "Status hints include the lower-left sidebar hint and the bottom status bar.": "状态提示包括左下角提示和底部状态栏。",
        "Font size": "字体大小",
        "Appearance": "外观",
        "Follow System": "跟随系统",
        "Light Appearance": "浅色模式",
        "Dark Appearance": "深色模式",
        "Reading and synthesis API key": "阅读与综述 API Key",
        "Fast profile-generation API key": "快速生成方向 API Key",
        "DeepSeek V4 Pro key for deep reading and memory synthesis": "DeepSeek V4 Pro Key（深读与记忆整合）",
        "DeepSeek V4 Flash key for profile generation": "DeepSeek V4 Flash Key（方向生成）",
        "DeepSeek keys saved to Keychain.": "DeepSeek API Key 已保存到钥匙串。",
        "Paste your DeepSeek API key here, then press Save to Keychain. The app stores it in macOS Keychain under service LiteratureRadarDeepSeekAPIKey. For command-line use, you can also run: export DEEPSEEK_API_KEY=sk-...": "DeepSeek V4 Pro Key 用于论文解读和长期记忆；DeepSeek V4 Flash Key 用于快速生成研究方向。两个 Key 会分别调用对应模型。",
        "Imported papers": "已导入论文",
        "Select papers to merge into the current profile's long-term memory.": "选择要融入当前研究方向长期记忆的论文。",
        "No Zotero import yet. Export RIS, BibTeX, or CSL JSON from Zotero and choose it here.": "还没有导入 Zotero 文件。请先从 Zotero 导出 RIS、BibTeX 或 CSL JSON，然后在这里选择。",
        "No Zotero import yet. Export BibTeX, RIS, or CSL JSON from Zotero and choose the export file or folder here. Local PDFs under files/ are read automatically when available.": "还没有导入 Zotero。请从 Zotero 导出 BibTeX、RIS 或 CSL JSON，然后在这里选择导出文件或文件夹；files/ 下的本地 PDF 会在可读取时自动读取。",
        "Zotero export tutorial": "Zotero 导出教程",
        "In Zotero, select papers, choose File > Export Items..., pick RIS, BibTeX, or CSL JSON, then import that file here.": "在 Zotero 中选中文献，点击 File > Export Items...，选择 RIS、BibTeX 或 CSL JSON，然后在这里导入该文件。",
        "In Zotero, select papers, choose File > Export Items..., pick BibTeX, RIS, or CSL JSON. If Zotero creates a folder with a .bib file plus a files/ PDF folder, you can select either the folder or the .bib file here.": "在 Zotero 中选中文献，点击 File > Export Items...，选择 BibTeX、RIS 或 CSL JSON。如果 Zotero 生成了一个包含 .bib 文件和 files/ PDF 文件夹的导出文件夹，这里既可以选择该文件夹，也可以选择里面的 .bib 文件。",
        "Initializing local database only. Use Demo or Run Radar after the app opens.": "仅初始化本地数据库。打开后可运行雷达联网搜索论文。",
        "Open Today Radar to search online papers.": "打开“今日雷达”会自动联网搜索新论文。",

        "Research OS": "科研操作系统",
        "Memory OS": "记忆操作系统",
        "Rebuilding knowledge tree": "重建知识树",
        "Assembling context packet": "组装工作记忆包",
        "Inspecting memory": "检查记忆系统",
        "Repairing memory": "修复记忆系统",
        "Literature Radar + Memory OS": "文献雷达 + 记忆操作系统",
        "Research Memory Operating System": "科研记忆操作系统",
        "Connect radar, deep reading, evidence, knowledge graph, interest, insights, and methods into a traceable research memory system.": "把雷达、深读、证据、知识图谱、兴趣、洞察和方法论连接成一个可追踪的科研记忆系统。",
        "Next Workflow": "下一步工作流",
        "Radar Discovery": "雷达发现",
        "Search and shallow reading only write events and interest states, without polluting factual knowledge.": "搜索和浅读只写入事件层和兴趣状态，不污染事实知识。",
        "DeepSeek Deep Read": "DeepSeek 深读",
        "Deep reading creates MemoryChangeSet, evidence spans, atomic knowledge, and insights.": "深读后生成 MemoryChangeSet、证据片段、原子知识和洞察。",
        "Consolidate and Repair": "巩固与纠错",
        "High-risk changes enter the review queue; every write keeps provenance and rollback clues.": "高风险变更进入审核队列；所有写入都有来源和回滚线索。",
        "Recent Candidates": "近期候选",
        "No papers yet. Load Demo or run Radar first.": "还没有论文。先加载示例或运行雷达。",
        "No papers yet. Open Today Radar or run Radar first.": "还没有论文。先打开“今日雷达”或运行雷达。",
        "Papers": "论文",
        "Knowledge Nodes": "知识节点",
        "Evidence": "证据",
        "Health": "健康度",
        "Local candidate library": "本地候选库",
        "Structured knowledge nodes": "结构化知识节点",
        "Traceable evidence spans": "可回溯证据片段",
        "Memory health": "记忆健康度",
        "No date": "无日期",
        "read": "已读",
        "local": "本地",
        "Local": "本地",
        "local_triage": "本地初筛",
        "deep_read": "深读",
        "Open": "打开",
        "Profile List": "方向列表",
        "Evidence, events, semantic knowledge graph, methods, metacognition, and working memory packets.": "证据层、事件层、语义知识图谱、方法论、元认知与工作记忆包。",
        "Rebuild Knowledge Tree": "重建知识树",
        "Inspect Memory": "检查记忆",
        "Auto Repair": "自动修复",
        "Dashboard": "仪表盘",
        "Knowledge Tree": "知识树",
        "Context Packet": "工作记忆包",
        "Notes": "笔记",
        "Review": "审核",
        "Interest States": "兴趣状态",
        "Recent Events": "最近事件",
        "No shallow interest signals yet.": "还没有浅层兴趣信号。",
        "No event memory yet.": "还没有事件记忆。",
        "event": "事件",
        "System Layer Counts": "系统层级计数",
        "Graph Overview": "图谱概览",
        "Nodes": "节点",
        "Edges": "边",
        "Confidence": "置信度",
        "No knowledge tree yet.": "暂无知识树。",
        "No metacognitive insights yet.": "暂无元认知洞察。",
        "Enter the current question or task to assemble a working memory packet": "输入当前问题或任务，让系统组装工作记忆包",
        "Assemble Context Packet": "组装工作记忆包",
        "packet": "工作包",
        "Active Direction": "当前方向",
        "Semantic": "语义知识",
        "Episodes": "事件",
        "Methodology": "方法论",
        "Metacognition": "元认知",
        "Forbidden Assumptions": "禁止假设",
        "No entries": "暂无条目",
        "This panel shows which semantic knowledge, evidence, events, methods, and metacognition are activated for a task.": "这里会显示一次任务临时激活了哪些语义知识、证据、事件、方法论和元认知。",
        "Preview": "预览",
        "risk": "风险",
        "pending": "待处理",
        "No high-risk memory changes need manual review.": "暂无需要人工审核的高风险记忆变更。",
        "Local-first; DeepSeek keys are stored in macOS Keychain.": "本地优先；DeepSeek key 存入 macOS 钥匙串。",
        "Saved keys are not displayed here, so opening Settings does not read Keychain. Leave a field blank to keep the saved value.": "已保存的 key 不会在这里显示，因此打开设置不会读取钥匙串。留空会保留已保存的值。",
        "Clear saved keys": "清空已保存 key",
        "Enter at least one API key to save.": "请至少输入一个要保存的 API Key。",
        "Could not save key": "无法保存 key",
        "Could not clear key": "无法清空 key",
        "%d imported candidates": "已导入 %d 篇候选论文",
        "No file was selected.": "未选择文件。",
        "Could not choose Zotero export": "无法选择 Zotero 导出内容",
        "No Zotero items found in the selected path.": "所选路径中没有找到 Zotero 条目。",
        "Imported %d Zotero papers.": "已导入 %d 篇 Zotero 论文。",
        "Select at least one imported paper.": "请至少选择一篇已导入论文。",
        "Exported %d Obsidian files.": "已导出 %d 个 Obsidian 文件。",
        "Exported %d Zotero files to %@.": "已导出 %d 个 Zotero 文件到 %@。",
        "Import Progress": "导入进度",
        "Integration Progress": "整合进度",
        "Scanning Zotero export": "正在扫描 Zotero 导出内容",
        "Parsing Zotero export": "正在解析 Zotero 导出文件",
        "Reading Zotero PDFs": "正在读取 Zotero PDF",
        "Saving imported papers": "正在保存导入论文",
        "Zotero import complete.": "Zotero 导入完成。",
        "Zotero import failed.": "Zotero 导入失败。",
        "Reading PDFs before LLM synthesis": "LLM 综合前读取 PDF",
        "Calling DeepSeek V4 Pro": "正在调用 DeepSeek V4 Pro",
        "Profile Generation Progress": "生成进度",
        "Preparing profile generation": "正在准备生成研究方向",
        "Calling DeepSeek V4 Flash": "正在调用 DeepSeek V4 Flash",
        "Saving generated profile": "正在保存生成的研究方向",
        "Profile generation failed.": "研究方向生成失败。",
        "Writing memory graph": "正在写入记忆图谱",
        "Term Guide": "术语说明",
        "Short source-backed passages extracted from papers.": "从论文里摘出的、可回溯到原文的关键句段。",
        "Concepts the app keeps as long-term research knowledge.": "系统认为值得长期保留的研究概念。",
        "A topic hierarchy built from those concepts.": "把这些概念按主题整理出来的层级树。",
        "A lightweight estimate of what you currently care about.": "系统对你近期关注主题的轻量估计。",
        "A log of actions such as reading, saving, feedback, and radar discovery.": "阅读、保存、反馈、雷达发现等操作记录。",
        "A temporary bundle of relevant memory for the current task.": "为当前任务临时调出的相关记忆包。",
        "High-risk memory changes that should be checked before trusting them.": "需要人工确认后再信任的高风险记忆变更。",
        "scanning": "扫描",
        "parsing": "解析",
        "reading_pdfs": "读取 PDF",
        "saving": "保存",
        "calling_llm": "LLM 处理",
        "writing_memory": "写入记忆",
        "preparing": "准备",
        "done": "完成",
        "failed": "失败",
        "memory notes": "记忆笔记",
        "papers": "论文",
        "paper chunks": "论文片段",
        "evidence spans": "证据片段",
        "knowledge nodes": "知识节点",
        "knowledge edges": "知识边",
        "atomic knowledge units": "原子知识单元",
        "methodology rules": "方法论规则",
        "metacognitive items": "元认知条目",
        "memory change sets": "记忆变更集",
        "pending review": "待审核",
        "draft nodes": "草稿节点",
        "orphan edges": "孤立边",
        "unbacked claims": "无证据论断",
        "paper_feedback": "论文反馈",
        "search_query": "搜索查询",
        "radar_candidate_found": "雷达候选发现",
        "shallow_analysis": "浅层分析",
        "research_direction_updated": "研究方向更新",
    ]
}
